<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\BoardGamesManagerCore\BoardGamesManagerCore.csproj" />
        <ProjectReference Include="..\BoardGamesManagerDataAccessLayer\EfCoreData\EfCoreData.csproj" />
        <ProjectReference Include="..\BoardGamesManagerDataAccessLayer\Models\Models.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
    </ItemGroup>

</Project>
